### ISSUE TITLE
Error:  list index out of range

### ISSUE THREAD

**Issue by sara-kassani** [amanrana20/Diabetic_Retinopathy_Detection#3]
Traceback (most recent call last):
  File "run.py", line 84, in <module>
    dl_model(sys.argv[1:]).execute()
  File "run.py", line 25, in __init__
    self.BASE_PATH = argv[0]
IndexError: list index out of range

**Comment by akkimah** [comment]
I also have the same issue please solve it and give the answer

**Comment by amanrana20** [comment]
Hi. The argv is arguments to the command line while running the code. So id your dataset is stored in /home/xyz/data/ then run using:

python run.py /home/xyz/data/

(Assuming you have the train and test folders in data folder.)

**Comment by akkimah** [comment]
Thank you so much @amanrana20...!!
